apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banished-ops-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/binaryn3xus/BanishedOps.git
    targetRevision:
    path: kubernetes/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Automatically create the namespace if it doesn't exist
