apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: it-tools
  namespace: argocd
spec:
  project: default
  source:
    chart: app-template
    targetRevision: 3.6.1
    repoURL: oci://ghcr.io/bjw-s/helm
    helm:
      secretRef:
        name: helm-credentials
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
